# Generated by Django 3.2.9 on 2021-12-17 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0004_extend_tag_support"),
        ("netbox_dns", "0007_alter_zone_soa_serial_auto"),
    ]

    operations = [
        migrations.AddField(
            model_name="zone",
            name="auto_renew",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name="zone",
            name="comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="zone",
            name="expire_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="zone",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="zones",
                to="tenancy.tenant",
            ),
        ),
    ]
