# Generated by Django 4.0.4 on 2022-04-16 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0007_contact_link"),
        ("netbox_dns", "0010_update_soa_records"),
    ]

    operations = [
        migrations.AddField(
            model_name="zone",
            name="auto_renew",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name="zone",
            name="comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="zone",
            name="expire_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="zone",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="zones",
                to="tenancy.tenant",
            ),
        ),
    ]
